ARG BASE_IMAGE=gitmesh-node-base:latest
FROM ${BASE_IMAGE}

COPY ./services/apps/webhook_api/package.json ./services/apps/webhook_api/pnpm-lock.yaml ./services/apps/webhook_api/tsconfig.json  ./services/apps/webhook_api/
COPY ./services/apps/webhook_api/config ./services/apps/webhook_api/config
COPY ./services/apps/webhook_api/src ./services/apps/webhook_api/src

RUN cd services/apps/webhook_api && pnpm install --frozen-lockfile
