ARG BASE_IMAGE=gitmesh-node-base:latest
FROM ${BASE_IMAGE}

COPY ./services/apps/integration_data_worker/package.json ./services/apps/integration_data_worker/pnpm-lock.yaml ./services/apps/integration_data_worker/tsconfig.json  ./services/apps/integration_data_worker/
COPY ./services/apps/integration_data_worker/config ./services/apps/integration_data_worker/config
COPY ./services/apps/integration_data_worker/src ./services/apps/integration_data_worker/src

RUN cd services/apps/integration_data_worker && pnpm install --frozen-lockfile
